[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "spoincd_projeto_final"
version = "0.0.1"
description = "Projeto final da disciplina Introdução à Ciência de Dados do curso Bacharelado em Sistemas de Informação do IFSP-SPO."
authors = [
  { name = "Felipe Teixeira de Lima" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "loguru",
    "mkdocs",
    "pip",
    "python-dotenv",
    "requests",
    "ruff",
    "tenacity",
    "tqdm",
    "typer",
]
requires-python = ">=3.13"


[tool.ruff]
line-length = 99
src = ["spoincd_projeto_final"]
include = ["pyproject.toml", "spoincd_projeto_final/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["spoincd_projeto_final"]
force-sort-within-sections = true

